name = "IntegralGrid"
uuid = "1ddb566f-c283-4f06-b132-c1434d206b41"
authors = ["YingXing Cheng"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
